index:
    path: /
    controller: App\Controller\DefaultController::index

teacher:
    path: /teacher
    controller: App\Controller\DefaultController::teacher

createQuestion:
    path: /teacher/questions
    controller: App\Controller\DefaultController::createQuestion

createExam:
    path: /teacher/exams
    controller: App\Controller\DefaultController::createExam

createAnswer:
    path: /teacher/questions/answers/{qId}
    controller: App\Controller\DefaultController::createAnswer

examQuestion:
    path: /teacher/exams/question/{eId}
    controller: App\Controller\DefaultController::examQuestion

randomExam:
    path: /teacher/exams/random/{eId}
    controller: App\Controller\DefaultController::randomExam

randomSelection:
    path: /teacher/exams/random/selection/{eId}
    controller: App\Controller\DefaultController::randomSelection

viewQuestion:
    path: /teacher/exams/random/view/exam/{eId}
    controller: App\Controller\DefaultController::viewQuestion


routeLevelControl:
    path: /routeLevelControl
    controller: App\Controller\DefaultController::LevelControl

student:
    path: /student
    controller: App\Controller\DefaultController::student

takeExam:
    path: /student/takeExam/{eId}
    controller: App\Controller\DefaultController::takeExam

takeAllExam:
    path: /student/takeExam/forEveryone/{tId}
    controller: App\Controller\DefaultController::takeAllExam

submitAnswers:
    path: /student/submitAnswers/{eId}
    controller: App\Controller\DefaultController::submitAnswers

submitAllAnswers:
    path: /student/submitAnswers/all/{eId}
    controller: App\Controller\DefaultController::submitAllAnswers

teacherResult:
    path: /teacher/result/
    controller: App\Controller\DefaultController::teacherResult

detailedResults:
    path: /teacher/result/detailed/{eId}
    controller: App\Controller\DefaultController::detailedResults

viewDetailedResult:
    path: /teacher/result/detailed/view/{eId}
    controller: App\Controller\DefaultController::viewDetailedResult

viewResult:
    path: /common/view/{eId}
    controller: App\Controller\DefaultController::viewResult

login:
    path: /login

logout:
    path: /logout
