index:
    path: /
    controller: App\Controller\DefaultController::index

teacher:
    path: /teacher
    controller: App\Controller\DefaultController::teacher

student:
    path: /student
    controller: App\Controller\DefaultController::student

createQuestion:
    path: /teacher/create/question
    controller: App\Controller\DefaultController::createQuestion

routeLevelControl:
    path: /routeLevelControl
    controller: App\Controller\DefaultController::LevelControl

login:
    path: /login

logout:
    path: /logout
