index:
    path: /
    controller: App\Controller\DefaultController::index

teacher:
    path: /teacher
    controller: App\Controller\DefaultController::teacher



createQuestion:
    path: /teacher/questions
    controller: App\Controller\DefaultController::createQuestion

createExam:
    path: /teacher/exams
    controller: App\Controller\DefaultController::createExam

createAnswer:
    path: /teacher/questions/answers/{qId}
    controller: App\Controller\DefaultController::createAnswer

examQuestion:
    path: /teacher/exams/question/{eId}
    controller: App\Controller\DefaultController::examQuestion

randomSelection:
    path: /teacher/exams/random/selection/{eId}
    controller: App\Controller\DefaultController::randomSelection

routeLevelControl:
    path: /routeLevelControl
    controller: App\Controller\DefaultController::LevelControl

student:
    path: /student
    controller: App\Controller\DefaultController::student

takeExam:
    path: /student/takeExam/{eId}
    controller: App\Controller\DefaultController::takeExam


submitAnswers:
    path: /student/submitAnswers/{eId}
    controller: App\Controller\DefaultController::submitAnswers

login:
    path: /login

logout:
    path: /logout
