index:
    path: /
    controller: App\Controller\DefaultController::index

teacher:
    path: /teacher
    controller: App\Controller\DefaultController::teacher

student:
    path: /student
    controller: App\Controller\DefaultController::student

createQuestion:
    path: /teacher/questions
    controller: App\Controller\DefaultController::createQuestion

createExam:
    path: /teacher/exams
    controller: App\Controller\DefaultController::createExam

createAnswer:
    path: /teacher/questions/answers/{qId}
    controller: App\Controller\DefaultController::createAnswer

routeLevelControl:
    path: /routeLevelControl
    controller: App\Controller\DefaultController::LevelControl

login:
    path: /login

logout:
    path: /logout
